Repository AOMediaCodec/av1-avif, pull requests merged in 2024-09, with the labels that each got.

#223 Fix use of <dfn value> and some indenting.
  index.bs
Labels: spec

#222 Add asserts for shoulds and shalls
  index.bs
Labels: conformance

#201 Fix issue #177
  testFiles/Netflix/avis/alpha_video.avif
Labels: conformance

#198 Changed Xiph multilayer test content to add lsel and nclx colr box
  testFiles/Xiph/abandoned_filmgrain.avif
  testFiles/Xiph/fruits_2layer_thumbsize.avif
  testFiles/Xiph/quebec_3layer_op2.avif
  testFiles/Xiph/tiger_3layer_1res.avif
  testFiles/Xiph/tiger_3layer_3res.avif
Labels: conformance

#199 Update testFiles/Link-U/kimono*.avif files to make them spec compliant
  testFiles/Link-U/kimono.avif
  testFiles/Link-U/kimono.mirror-horizontal.avif
  testFiles/Link-U/kimono.mirror-vertical.avif
  testFiles/Link-U/kimono.mirror-vertical.rotate270.avif
  testFiles/Link-U/kimono.rotate270.avif
  testFiles/Link-U/kimono.rotate90.avif
Labels: conformance

#210 Added AVIF sanitizer tool
  Tools/sanitize_avif.py
Labels: tools

#224 Sample transform
  index.bs
Labels: spec
